version: '3'
services:
  auth-service:
    build:
      context: AuthService/.
      dockerfile: ./Dockerfile
      args:
        DbConnection: ${AuthDbConnection}
        ServiceBusConnection: ${ServiceBusConnection}
  calendar-service:
    build:
      context: CalendarService/.
      dockerfile: ./Dockerfile
      args:
        DbConnection: ${CalendarDbConnection}
        ServiceBusConnection: ${ServiceBusConnection}
